import tiptap2typst from "../compilers/tiptap2typst"
import { TyXDocument } from "../models"

export const document2typst = (document: TyXDocument, version: string) => {
  let content = `// Automatically generated by TyX ${version}.\n`
  if (document.preamble) {
    content += document.preamble + "\n"
  }
  content += tiptap2typst(document.content)
  return content
}
