import { createCommand, LexicalCommand } from "lexical"

export const TOGGLE_KEYBOARD_MAP_COMMAND: LexicalCommand<string | null> =
  createCommand()

export const KEYBOARD_MAPS: Record<string, Record<string, string>> = {
  Hebrew: {
    a: "ש",
    b: "נ",
    c: "ב",
    d: "ג",
    e: "ק",
    f: "כ",
    g: "ע",
    h: "י",
    i: "ן",
    j: "ח",
    k: "ל",
    l: "ך",
    m: "צ",
    n: "מ",
    o: "ם",
    p: "פ",
    q: "/",
    r: "ר",
    s: "ד",
    t: "א",
    u: "ו",
    v: "ה",
    w: "'",
    x: "ס",
    y: "ט",
    z: "ז",
    ",": "ת",
    ".": "ץ",
    ";": "ף",
    "'": ",",
    "/": ".",
    "`": ";",
    "(": ")",
    ")": "(",
    "[": "]",
    "]": "[",
    "{": "}",
    "}": "{",
    "<": ">",
    ">": "<",
  },
}
